services:
  web:
    build: .
    command: >
      sh -c "python exchange/manage.py migrate &&
             python exchange/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./exchange:/app/exchange
    ports:
      - "8000:8000"  # Пробрасываем порт
    depends_on:
      - db
    env_file:
        - .env

  db:
    image: postgres:alpine  
    restart: always
    env_file:
        - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохраняем данные между запусками

volumes:
  postgres_data: